import { ArrowLeft, ArrowRight, Pencil, Package, ShoppingCart, Wallet } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import i18n, { displayUnit, localeForDates } from "./i18n/index.js";
import { apiFetch } from "./i18n/apiFetch.js";

const t = i18n.t.bind(i18n);

type Item = { id:string; name:string; sku:string; barcode?:string|null; category:string; baseUnit:string; consumptionType?:"non_consumable"|"consumable"|"long_term_consumable"; openedShelfLifeDays?:number|null; reorderPoint:number; reorderQuantity:number; locationId?:string|null; locationName?:string|null; lastUnitPrice?:number|null; currency?:string|null };
type Batch = { batchId:string; locationId:string; locationName:string; quantity:number; expiryDate:string|null; totalPrice:number|null; unitPrice:number|null; purchaseCurrency:string|null; purchasedDate:string|null; channelName:string|null };
type PriceRecord = { batchId:string; purchaseDate:string|null; channelName:string|null; totalPrice:number; quantity:number; unitPrice:number|null; currency:string };
type Transaction = {id:string;locationName:string|null;type:"receipt"|"issue"|"delete"|"reclassify"|"move"|"update";quantity:number|null;reason:string|null;issueReason:"used"|"expired"|"damaged"|"adjustment"|null;occurredAt:string;batchId:string|null};
type TransactionPage = {items:Transaction[];total:number;offset:number;limit:number;hasMore:boolean;snapshotAt:string};

export function ItemDetail({homeId,item,currency,onBack,onEdit}:{homeId:string;item:Item;currency:string;onBack:()=>void;onEdit:()=>void}) {
  const [batches,setBatches]=useState<Batch[]>([]);
  const [prices,setPrices]=useState<PriceRecord[]>([]);
  const [transactions,setTransactions]=useState<TransactionPage|null>(null);
  const [transactionPage,setTransactionPage]=useState(1);
  const [transactionError,setTransactionError]=useState("");
  const [error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController();setError("");Promise.all([
    apiFetch(`/api/v1/homes/${homeId}/batches?itemId=${item.id}&includeEmpty=false&limit=100`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(t("无法加载批次"));return response.json();}),
    apiFetch(`/api/v1/homes/${homeId}/items/${item.id}/price-history`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(t("无法加载价格统计"));return response.json();}),
  ]).then(([batchData,priceData])=>{setBatches(batchData.items);setPrices(priceData.items);}).catch(value=>{if(value.name!=="AbortError")setError(value.message);});return()=>controller.abort();},[homeId,item.id]);
  useEffect(()=>{const controller=new AbortController();setTransactionError("");apiFetch(`/api/v1/homes/${homeId}/transactions?itemId=${item.id}&limit=10&offset=${(transactionPage-1)*10}${transactions?.snapshotAt?`&snapshotAt=${encodeURIComponent(transactions.snapshotAt)}`:""}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(t("无法加载变动记录"));return response.json();}).then(setTransactions).catch(value=>{if(value.name!=="AbortError")setTransactionError(value.message);});return()=>controller.abort();},[homeId,item.id,transactionPage]);
  useEffect(()=>{setTransactionPage(1);setTransactions(null);},[homeId,item.id]);
  const number=(value:number,recordCurrency=currency)=>new Intl.NumberFormat(localeForDates(),{style:"currency",currency:recordCurrency||"CNY"}).format(value);
  const quantity=batches.reduce((total,batch)=>total+batch.quantity,0);
  const value=batches.reduce((total,batch)=>total+(batch.totalPrice!==null&&batch.unitPrice!==null?batch.quantity*batch.unitPrice:0),0);
  const knownBatches=batches.filter(batch=>batch.totalPrice!==null).length;
  const stats=useMemo(()=>{const values=prices.flatMap(row=>row.unitPrice===null?[]:[row.unitPrice]);if(!values.length)return null;return {latest:values[0],lowest:Math.min(...values),average:values.reduce((sum,value)=>sum+value,0)/values.length};},[prices]);
  const chart=[...prices].reverse().flatMap(row=>row.unitPrice===null?[]:[row]);
  const chartMax=Math.max(1,...chart.map(row=>row.unitPrice??0));
  const transactionLabels={receipt:t("入库"),issue:t("领用"),delete:t("删除"),reclassify:t("分类变更"),move:t("位置变更"),update:t("批次变更")};
  const issueReasonLabels={used:t("正常使用"),expired:t("过期报废"),damaged:t("损坏"),adjustment:t("盘点调整")};
  const transactionPages=Math.max(1,Math.ceil((transactions?.total??0)/10));
  return <section className="item-detail-page">
    <style>{`.item-detail-page { grid-template-columns: minmax(0, 1fr); } @media (max-width: 700px) { .item-detail-page { min-width: 0; overflow: hidden; } .item-detail-grid { min-width: 0; max-width: 100%; grid-template-columns: 1fr; } .item-price-panel, .item-info-panel { min-width: 0; max-width: 100%; } } .item-detail-head > div, .item-detail-grid > * { min-width: 0; } .item-detail-edit { flex: none; } .price-stat-grid, .price-chart { min-width: 0; } .price-stat-grid > div { min-width: 0; } .price-stat-grid small { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }`}</style>
    <div className="item-detail-head"><button type="button" className="back-button" onClick={onBack} aria-label={t("返回")}><ArrowLeft size={18}/></button><div><p className="item-detail-kicker">{item.category}</p><h1>{item.name}</h1><p className="muted">{item.sku}{item.barcode?` · ${item.barcode}`:""}</p></div><button type="button" className="secondary item-detail-edit" onClick={onEdit}><Pencil size={14}/>{t("编辑")}</button></div>
    {error&&<p className="setup-error" role="alert">{error}</p>}
    <section className="item-detail-summary"><div><Package size={17}/><small>{t("当前库存")}</small><strong>{quantity} {displayUnit(item.baseUnit)}</strong><span>{t("最低库存")} {item.reorderPoint} {displayUnit(item.baseUnit)}</span></div><div><Wallet size={17}/><small>{t("库存价值")}</small><strong>{number(value)}</strong><span>{t("已计价批次")} {knownBatches} / {batches.length}</span></div><div><ShoppingCart size={17}/><small>{t("最近单价")}</small><strong>{stats?number(stats.latest):t("未知")}</strong><span>{item.locationName||t("未指定存放地点")}</span></div></section>
    <section className="item-detail-grid"><section className="panel item-price-panel"><div className="panel-head"><div><h2>{t("价格趋势")}</h2><p className="muted">{t("按采购日期的单位价格")}</p></div></div>{stats?<><div className="price-stat-grid"><div><small>{t("最近单价")}</small><b>{number(stats.latest)}</b></div><div><small>{t("历史最低价")}</small><b>{number(stats.lowest)}</b></div><div><small>{t("平均单价")}</small><b>{number(stats.average)}</b></div></div><div className="price-chart" aria-label={t("价格趋势")}>{chart.map(row=><div className="price-column" key={row.batchId} title={`${row.purchaseDate||t("未设置")} · ${number(row.unitPrice??0,row.currency)}`}><i style={{height:`${(row.unitPrice??0)/chartMax*100}%`}}/><small>{row.purchaseDate?.slice(5)||"-"}</small></div>)}</div></>:<p className="empty">{t("暂无已录入价格")}</p>}</section><section className="panel item-info-panel"><div className="panel-head"><div><h2>{t("物资信息")}</h2><p className="muted">{t("基础资料与补货阈值")}</p></div></div><dl><div><dt>{t("分类")}</dt><dd>{item.category}</dd></div><div><dt>{t("单位")}</dt><dd>{displayUnit(item.baseUnit)}</dd></div><div><dt>{t("消耗类型")}</dt><dd>{item.consumptionType==="long_term_consumable"?t("长期消耗品"):item.consumptionType==="non_consumable"?t("非消耗品"):t("消耗品")}</dd></div><div><dt>{t("开封后保质期（天）")}</dt><dd>{item.openedShelfLifeDays??t("未设置")}</dd></div><div><dt>{t("默认地点")}</dt><dd>{item.locationName||t("未指定")}</dd></div><div><dt>{t("补货数量")}</dt><dd>{item.reorderQuantity} {displayUnit(item.baseUnit)}</dd></div></dl></section></section>
    <section className="panel item-detail-table"><div className="panel-head"><div><h2>{t("购买记录")}</h2><p className="muted">{t("已录入成本的采购批次")}</p></div></div><div className="table-wrap"><table><thead><tr><th>{t("采购日期")}</th><th>{t("渠道")}</th><th>{t("数量")}</th><th>{t("单价")}</th><th>{t("实付总价")}</th></tr></thead><tbody>{prices.length?prices.map(row=><tr key={row.batchId}><td>{row.purchaseDate||t("未设置")}</td><td>{row.channelName||t("未指定")}</td><td>{row.quantity} {displayUnit(item.baseUnit)}</td><td>{row.unitPrice===null?t("未知"):number(row.unitPrice,row.currency)}</td><td>{number(row.totalPrice,row.currency)}</td></tr>):<tr><td colSpan={5} className="empty">{t("暂无已录入价格")}</td></tr>}</tbody></table></div></section>
    <section className="panel item-detail-table"><div className="panel-head"><div><h2>{t("库存批次")}</h2><p className="muted">{t("按地点和批次查看剩余库存")}</p></div></div><div className="table-wrap"><table><thead><tr><th>{t("地点")}</th><th>{t("剩余")}</th><th>{t("到期日期")}</th><th>{t("单价")}</th><th>{t("剩余价值")}</th></tr></thead><tbody>{batches.length?batches.map(batch=><tr key={`${batch.batchId}:${batch.locationId}`}><td>{batch.locationName||t("未指定")}</td><td>{batch.quantity} {displayUnit(item.baseUnit)}</td><td>{batch.expiryDate||t("未设置")}</td><td>{batch.unitPrice===null?t("未知"):number(batch.unitPrice,batch.purchaseCurrency??currency)}</td><td>{batch.unitPrice===null?t("未知"):number(batch.unitPrice*batch.quantity,batch.purchaseCurrency??currency)}</td></tr>):<tr><td colSpan={5} className="empty">{t("暂无批次")}</td></tr>}</tbody></table></div></section>
    <section className="panel item-detail-table item-transaction-history"><div className="panel-head"><div><h2>{t("变动记录")}</h2><p className="muted">{t("最近 10 条库存变动")}</p></div></div>{transactionError?<p className="empty" role="alert">{transactionError}</p>:<><div className="table-wrap"><table><thead><tr><th>{t("时间")}</th><th>{t("变动类型")}</th><th>{t("数量")}</th><th>{t("地点")}</th><th>{t("批次")}</th><th>{t("原因")}</th></tr></thead><tbody>{transactions?.items.length?transactions.items.map(row=><tr key={row.id}><td>{new Date(row.occurredAt).toLocaleString(localeForDates(),{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}</td><td>{row.type==="issue"&&row.issueReason?issueReasonLabels[row.issueReason]:transactionLabels[row.type]}</td><td>{row.quantity===null?"—":`${row.type==="issue"?"−":row.type==="receipt"?"+":""}${row.quantity} ${displayUnit(item.baseUnit)}`}</td><td>{row.locationName||t("未指定")}</td><td>{row.batchId?.slice(0,8)??"—"}</td><td>{row.reason||"—"}</td></tr>):<tr><td colSpan={6} className="empty">{t("暂无变动记录")}</td></tr>}</tbody></table></div>{transactions&&transactionPages>1&&<div className="pagination item-history-pagination"><span>{transactions.offset+1}–{Math.min(transactions.offset+transactions.items.length,transactions.total)} {t("/ 共")} {transactions.total} {t("条")}</span><button type="button" aria-label={t("上一页")} disabled={transactionPage===1} onClick={()=>setTransactionPage(page=>page-1)}><ArrowLeft size={15}/></button><span>{transactionPage} / {transactionPages}</span><button type="button" aria-label={t("下一页")} disabled={!transactions.hasMore} onClick={()=>setTransactionPage(page=>page+1)}><ArrowRight size={15}/></button></div>}</>}</section>
  </section>;
}
