import assert from "node:assert/strict";
import { createHash, randomBytes, randomUUID, scryptSync } from "node:crypto";
import { test } from "node:test";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { openDatabase } from "@al1s-wms/db";
import { buildApp } from "./app.js";
import { createMcpServer } from "./mcp.js";
import { recordStock } from "./stock.js";

const parseTool = (result:unknown) =>
  JSON.parse(((result as {content:{type:string;text:string}[]}).content)[0].text);

test("home-scoped tokens isolate REST and simplify MCP tool inputs", async () => {
  process.env.NODE_ENV="test";
  const db=openDatabase(":memory:");
  const homeId=randomUUID(),otherHomeId=randomUUID(),locationId=randomUUID(),itemId=randomUUID(),userId=randomUUID();
  db.prepare("INSERT INTO homes(id,name) VALUES (?,?),(?,?)").run(homeId,"本家",otherHomeId,"其他家");
  db.prepare("INSERT INTO locations(id,home_id,name) VALUES (?,?,?)").run(locationId,homeId,"储物柜");
  db.prepare("INSERT INTO items(id,home_id,sku,barcode,name,category,base_unit,reorder_point,default_location_id) VALUES (?,?,?,?,?,?,?,?,?)").run(itemId,homeId,itemId,"3017620422003","牛奶","食品","瓶",3,locationId);
  const username=randomUUID(),salt=randomBytes(16).toString("hex");
  db.prepare("INSERT INTO users(id,username,password_hash,created_at) VALUES (?,?,?,?)").run(userId,username,`${salt}:${scryptSync("old-password",salt,64).toString("hex")}`,new Date().toISOString());
  const sessionId=randomUUID();
  db.prepare("INSERT INTO sessions(id,user_id,expires_at) VALUES (?,?,?)").run(sessionId,userId,new Date(Date.now()+86400000).toISOString());
  const addToken=(home:string|null) => {
    const token=`al1s_${randomUUID().replaceAll("-","")}${randomUUID().replaceAll("-","")}`;
    db.prepare("INSERT INTO api_tokens(id,user_id,home_id,name,token_hash,token_prefix,created_at) VALUES (?,?,?,?,?,?,?)").run(randomUUID(),userId,home,"test",createHash("sha256").update(token).digest("hex"),token.slice(0,13),new Date().toISOString());
    return token;
  };
  const homeToken=addToken(homeId),accountToken=addToken(null);
  const app=await buildApp(db);
  const request=async(token:string,method:"GET"|"POST"|"PATCH"|"DELETE",url:string,body?:Record<string,unknown>)=>{
    const response=await app.inject({method,url,headers:{authorization:`Bearer ${token}`},payload:body});
    return {status:response.statusCode,body:response.json()};
  };
  assert.equal((await request(homeToken,"GET",`/api/v1/homes/${homeId}/items`)).status,200);
  assert.equal((await request(homeToken,"GET",`/api/v1/homes/${otherHomeId}/items`)).status,403);
  assert.equal(((await request(homeToken,"GET","/api/v1/homes")).body as unknown[]).length,1);
  assert.equal(((await request(accountToken,"GET","/api/v1/homes")).body as unknown[]).length,2);
  const currencyUpdate=await request(homeToken,"PATCH",`/api/v1/homes/${homeId}`,{name:"本家",icon:"house",defaultCurrency:"USD"});
  assert.equal(currencyUpdate.status,200);
  const channels=(await request(homeToken,"GET",`/api/v1/homes/${homeId}/shopping-channels`)).body as {id:string;name:string}[];
  assert.equal(channels.length,9);
  const planned=await request(homeToken,"POST",`/api/v1/homes/${homeId}/shopping-list`,{itemId,quantity:1,channelId:channels[0].id,plannedDate:"2026-10-08"});
  assert.equal(planned.status,201);
  const plannedId=(planned.body as {id:string}).id;
  const shopping=(await request(homeToken,"GET",`/api/v1/homes/${homeId}/shopping-list`)).body as {itemId:string;source:string}[];
  assert.equal(shopping.filter(entry=>entry.itemId===itemId).length,1,"persisted plans suppress duplicate automatic suggestions");
  const calendar=await request(homeToken,"GET",`/api/v1/homes/${homeId}/shopping-calendar?month=2026-10&includeCompleted=false`);
  assert.equal((calendar.body as {plannedDate:string}[])[0].plannedDate,"2026-10-08");
  const createdToken=await app.inject({method:"POST",url:"/api/v1/auth/tokens",headers:{cookie:`session=${sessionId}`},payload:{name:"家庭 Agent",homeId}});
  assert.equal(createdToken.statusCode,201);
  assert.equal(db.prepare("SELECT home_id FROM api_tokens WHERE id=?").get(createdToken.json().id)?.home_id,homeId);
  const missingScope=await app.inject({method:"POST",url:"/api/v1/auth/tokens",headers:{cookie:`session=${sessionId}`},payload:{name:"无范围"}});
  assert.equal(missingScope.statusCode,400);
  assert.equal((await app.inject({method:"DELETE",url:`/api/v1/auth/tokens/${createdToken.json().id}`,headers:{cookie:`session=${sessionId}`}})).statusCode,200);
  const activeTokens=(await app.inject({method:"GET",url:"/api/v1/auth/tokens",headers:{cookie:`session=${sessionId}`}})).json() as {id:string}[];
  assert.equal(activeTokens.some(token=>token.id===createdToken.json().id),false);
  const currentUser=(await app.inject({method:"GET",url:"/api/v1/auth/me",headers:{cookie:`session=${sessionId}`}})).json() as {avatar:string};
  assert.equal(currentUser.avatar,"user");
  const avatarUpdate=await app.inject({method:"PATCH",url:"/api/v1/auth/me",headers:{cookie:`session=${sessionId}`},payload:{avatar:"bot"}});
  assert.equal(avatarUpdate.statusCode,200);
  assert.equal(avatarUpdate.json().avatar,"bot");
  assert.equal((await app.inject({method:"GET",url:"/api/v1/auth/me",headers:{cookie:`session=${sessionId}`}})).json().avatar,"bot");
  assert.equal((await app.inject({method:"PATCH",url:"/api/v1/auth/me",headers:{cookie:`session=${sessionId}`},payload:{avatar:"invalid"}})).statusCode,400);
  assert.equal((await app.inject({method:"POST",url:"/api/v1/auth/password",headers:{cookie:`session=${sessionId}`},payload:{currentPassword:"wrong",newPassword:"new-password"}})).statusCode,401);
  assert.equal((await app.inject({method:"POST",url:"/api/v1/auth/password",headers:{cookie:`session=${sessionId}`},payload:{currentPassword:"old-password",newPassword:"new-password"}})).statusCode,200);
  assert.equal((await app.inject({method:"POST",url:"/api/v1/auth/login",payload:{username,password:"old-password"}})).statusCode,401);
  assert.equal((await app.inject({method:"POST",url:"/api/v1/auth/login",payload:{username,password:"new-password"}})).statusCode,200);

  const server=createMcpServer((method,url,body)=>request(homeToken,method,url,body),homeId);
  const client=new Client({name:"workflow-test",version:"1"});
  const [clientTransport,serverTransport]=InMemoryTransport.createLinkedPair();
  await server.connect(serverTransport);await client.connect(clientTransport);
  const tools=await client.listTools();
  const receipt=tools.tools.find(tool=>tool.name==="record_receipt")!;
  assert.equal("homeId" in (receipt.inputSchema.properties??{}),false);
  assert.equal("reason" in (receipt.inputSchema.properties??{}),false);
  assert.equal("totalPrice" in (receipt.inputSchema.properties??{}),true);
  const issue=tools.tools.find(tool=>tool.name==="record_issue")!;
  assert.equal("issueReason" in (issue.inputSchema.properties??{}),true);
  assert.equal((issue.inputSchema.required??[]).includes("issueReason"),true);
  const createItem=tools.tools.find(tool=>tool.name==="create_item")!;
  assert.equal("consumptionType" in (createItem.inputSchema.properties??{}),true);
  assert.match(String(((createItem.inputSchema.properties??{}).consumptionType as {description?:string}|undefined)?.description),/long_term_consumable/);
  assert.ok(tools.tools.some(tool=>tool.name==="list_opened_consumables"));
  assert.ok(tools.tools.some(tool=>tool.name==="exhaust_opened_consumable"));
  assert.equal("reason" in (tools.tools.find(tool=>tool.name==="transfer_stock")!.inputSchema.properties??{}),false);
  const context=parseTool(await client.callTool({name:"get_home_context",arguments:{}}));
  assert.equal(context.scope,"home");
  assert.equal(context.currentHome.id,homeId);
  const guide=parseTool(await client.callTool({name:"get_agent_guide",arguments:{}}));
  assert.equal(guide.receipt.length,4);
  const barcode=parseTool(await client.callTool({name:"lookup_barcode",arguments:{barcode:"3017620422003"}}));
  assert.equal(barcode.source,"inventory");
  assert.equal(barcode.item.id,itemId);
  const received=parseTool(await client.callTool({name:"record_receipt",arguments:{itemId,locationId,quantity:2,idempotencyKey:"mcp-receipt",expiryDate:"2027-01-01"}}));
  assert.equal(received.beforeQuantity,0);
  assert.equal(received.afterQuantity,2);
  const overview=parseTool(await client.callTool({name:"get_home_overview",arguments:{}}));
  assert.equal(overview.needsReplenishment.total,1);
  const finance=parseTool(await client.callTool({name:"get_financial_summary",arguments:{month:"2026-09"}}));
  assert.equal(finance.currency,"USD");
  const savedBudget=parseTool(await client.callTool({name:"set_financial_budget",arguments:{month:"2026-10",total:30,categoryBudgets:[{category:"食品",amount:10},{category:"日用品",amount:5}]}}));
  assert.equal(savedBudget.budgetTotal,30);
  const receivedShopping=parseTool(await client.callTool({name:"receive_shopping_item",arguments:{shoppingItemId:plannedId,actualQuantity:1,totalPrice:4,purchaseDate:"2026-10-08",idempotencyKey:"mcp-shopping-receipt"}}));
  assert.equal(receivedShopping.completed,true);
  db.prepare("UPDATE stock_batches SET received_at='2026-10-08T10:00:00.000Z' WHERE shopping_item_id=?").run(plannedId);
  const activeShopping=parseTool(await client.callTool({name:"list_shopping_items",arguments:{}})) as {id:string}[];
  assert.equal(activeShopping.some(item=>item.id===plannedId),false);
  const dashboard=parseTool(await client.callTool({name:"get_financial_dashboard",arguments:{month:"2026-10"}}));
  assert.equal(dashboard.byCategory.find((row:{category:string})=>row.category==="食品").budget,10);
  assert.equal(dashboard.purchases[0].shoppingItemId,plannedId);
  const mcpCalendar=parseTool(await client.callTool({name:"get_shopping_calendar",arguments:{month:"2026-10",includeCompleted:true}}));
  assert.equal(mcpCalendar[0].channelName,channels[0].name);
  const updateUrl=`/api/v1/homes/${homeId}/items/${itemId}`;
  assert.equal((await request(homeToken,"PATCH",updateUrl,{category:"饮品"})).status,200);
  assert.equal(db.prepare("SELECT purchase_category FROM stock_batches WHERE item_id=?").get(itemId)?.purchase_category,"食品");
  assert.equal((await request(homeToken,"PATCH",updateUrl,{category:"乳品",syncPurchaseCategory:true})).status,200);
  assert.equal(db.prepare("SELECT purchase_category FROM stock_batches WHERE item_id=?").get(itemId)?.purchase_category,"乳品");
  const secondLocationId=randomUUID();
  db.prepare("INSERT INTO locations(id,home_id,name) VALUES (?,?,?)").run(secondLocationId,homeId,"客厅储物架");
  recordStock(db,homeId,"receipt",{itemId,locationId:secondLocationId,quantity:3,idempotencyKey:"recent-location-receipt"});
  db.prepare("UPDATE stock_transactions SET occurred_at='2026-09-18T18:00:00.000Z' WHERE item_id=? AND location_id=?").run(itemId,locationId);
  db.prepare("UPDATE stock_transactions SET occurred_at='2026-09-18T19:00:00.000Z' WHERE item_id=? AND location_id=?").run(itemId,secondLocationId);
  const stockRows=(await request(homeToken,"GET",`/api/v1/homes/${homeId}/stock?itemId=${itemId}`)).body as {locationId:string;latestReceivedAt:string}[];
  assert.deepEqual(new Map(stockRows.map(row=>[row.locationId,row.latestReceivedAt])),new Map([[locationId,"2026-09-18T18:00:00.000Z"],[secondLocationId,"2026-09-18T19:00:00.000Z"]]));
  await client.close();await server.close();

  const accountServer=createMcpServer((method,url,body)=>request(accountToken,method,url,body));
  const accountClient=new Client({name:"account-test",version:"1"});
  const [accountClientTransport,accountServerTransport]=InMemoryTransport.createLinkedPair();
  await accountServer.connect(accountServerTransport);await accountClient.connect(accountClientTransport);
  const accountTools=await accountClient.listTools();
  assert.equal("homeId" in (accountTools.tools.find(tool=>tool.name==="record_receipt")!.inputSchema.properties??{}),true);
  await accountClient.close();await accountServer.close();await app.close();db.close();
});
