import assert from "node:assert/strict";
import { createHash, randomBytes, randomUUID, scryptSync } from "node:crypto";
import { test } from "node:test";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { openDatabase } from "@family-erp/db";
import { buildApp } from "./app.js";
import { createMcpServer } from "./mcp.js";

const parseTool = (result:unknown) =>
  JSON.parse(((result as {content:{type:string;text:string}[]}).content)[0].text);

test("home-scoped tokens isolate REST and simplify MCP tool inputs", async () => {
  process.env.NODE_ENV="test";
  const db=openDatabase(":memory:");
  const homeId=randomUUID(),otherHomeId=randomUUID(),locationId=randomUUID(),itemId=randomUUID(),userId=randomUUID();
  db.prepare("INSERT INTO homes(id,name) VALUES (?,?),(?,?)").run(homeId,"本家",otherHomeId,"其他家");
  db.prepare("INSERT INTO locations(id,home_id,name) VALUES (?,?,?)").run(locationId,homeId,"储物柜");
  db.prepare("INSERT INTO items(id,home_id,sku,barcode,name,category,base_unit,reorder_point,default_location_id) VALUES (?,?,?,?,?,?,?,?,?)").run(itemId,homeId,itemId,"3017620422003","牛奶","食品","瓶",3,locationId);
  const username=randomUUID(),salt=randomBytes(16).toString("hex");
  db.prepare("INSERT INTO users(id,username,password_hash,created_at) VALUES (?,?,?,?)").run(userId,username,`${salt}:${scryptSync("old-password",salt,64).toString("hex")}`,new Date().toISOString());
  const sessionId=randomUUID();
  db.prepare("INSERT INTO sessions(id,user_id,expires_at) VALUES (?,?,?)").run(sessionId,userId,new Date(Date.now()+86400000).toISOString());
  const addToken=(home:string|null) => {
    const token=`al1s_${randomUUID().replaceAll("-","")}${randomUUID().replaceAll("-","")}`;
    db.prepare("INSERT INTO api_tokens(id,user_id,home_id,name,token_hash,token_prefix,created_at) VALUES (?,?,?,?,?,?,?)").run(randomUUID(),userId,home,"test",createHash("sha256").update(token).digest("hex"),token.slice(0,13),new Date().toISOString());
    return token;
  };
  const homeToken=addToken(homeId),accountToken=addToken(null);
  const app=await buildApp(db);
  const request=async(token:string,method:"GET"|"POST"|"PATCH"|"DELETE",url:string,body?:Record<string,unknown>)=>{
    const response=await app.inject({method,url,headers:{authorization:`Bearer ${token}`},payload:body});
    return {status:response.statusCode,body:response.json()};
  };
  assert.equal((await request(homeToken,"GET",`/api/v1/homes/${homeId}/items`)).status,200);
  assert.equal((await request(homeToken,"GET",`/api/v1/homes/${otherHomeId}/items`)).status,403);
  assert.equal(((await request(homeToken,"GET","/api/v1/homes")).body as unknown[]).length,1);
  assert.equal(((await request(accountToken,"GET","/api/v1/homes")).body as unknown[]).length,2);
  const channels=(await request(homeToken,"GET",`/api/v1/homes/${homeId}/shopping-channels`)).body as {id:string;name:string}[];
  assert.equal(channels.length,9);
  const planned=await request(homeToken,"POST",`/api/v1/homes/${homeId}/shopping-list`,{itemId,quantity:1,channelId:channels[0].id,plannedDate:"2026-10-08"});
  assert.equal(planned.status,201);
  const shopping=(await request(homeToken,"GET",`/api/v1/homes/${homeId}/shopping-list`)).body as {itemId:string;source:string}[];
  assert.equal(shopping.filter(entry=>entry.itemId===itemId).length,1,"persisted plans suppress duplicate automatic suggestions");
  const calendar=await request(homeToken,"GET",`/api/v1/homes/${homeId}/shopping-calendar?month=2026-10&includeCompleted=false`);
  assert.equal((calendar.body as {plannedDate:string}[])[0].plannedDate,"2026-10-08");
  assert.equal((await request(homeToken,"DELETE",`/api/v1/homes/${homeId}/shopping-channels/${channels[0].id}`)).status,409);
  const createdToken=await app.inject({method:"POST",url:"/api/v1/auth/tokens",headers:{cookie:`session=${sessionId}`},payload:{name:"家庭 Agent",homeId}});
  assert.equal(createdToken.statusCode,201);
  assert.equal(db.prepare("SELECT home_id FROM api_tokens WHERE id=?").get(createdToken.json().id)?.home_id,homeId);
  const missingScope=await app.inject({method:"POST",url:"/api/v1/auth/tokens",headers:{cookie:`session=${sessionId}`},payload:{name:"无范围"}});
  assert.equal(missingScope.statusCode,400);
  assert.equal((await app.inject({method:"DELETE",url:`/api/v1/auth/tokens/${createdToken.json().id}`,headers:{cookie:`session=${sessionId}`}})).statusCode,200);
  const activeTokens=(await app.inject({method:"GET",url:"/api/v1/auth/tokens",headers:{cookie:`session=${sessionId}`}})).json() as {id:string}[];
  assert.equal(activeTokens.some(token=>token.id===createdToken.json().id),false);
  assert.equal((await app.inject({method:"POST",url:"/api/v1/auth/password",headers:{cookie:`session=${sessionId}`},payload:{currentPassword:"wrong",newPassword:"new-password"}})).statusCode,401);
  assert.equal((await app.inject({method:"POST",url:"/api/v1/auth/password",headers:{cookie:`session=${sessionId}`},payload:{currentPassword:"old-password",newPassword:"new-password"}})).statusCode,200);
  assert.equal((await app.inject({method:"POST",url:"/api/v1/auth/login",payload:{username,password:"old-password"}})).statusCode,401);
  assert.equal((await app.inject({method:"POST",url:"/api/v1/auth/login",payload:{username,password:"new-password"}})).statusCode,200);

  const server=createMcpServer((method,url,body)=>request(homeToken,method,url,body),homeId);
  const client=new Client({name:"workflow-test",version:"1"});
  const [clientTransport,serverTransport]=InMemoryTransport.createLinkedPair();
  await server.connect(serverTransport);await client.connect(clientTransport);
  const tools=await client.listTools();
  const receipt=tools.tools.find(tool=>tool.name==="record_receipt")!;
  assert.equal("homeId" in (receipt.inputSchema.properties??{}),false);
  assert.equal("reason" in (receipt.inputSchema.properties??{}),false);
  assert.equal("reason" in (tools.tools.find(tool=>tool.name==="transfer_stock")!.inputSchema.properties??{}),false);
  const context=parseTool(await client.callTool({name:"get_home_context",arguments:{}}));
  assert.equal(context.scope,"home");
  assert.equal(context.currentHome.id,homeId);
  const guide=parseTool(await client.callTool({name:"get_agent_guide",arguments:{}}));
  assert.equal(guide.receipt.length,4);
  const barcode=parseTool(await client.callTool({name:"lookup_barcode",arguments:{barcode:"3017620422003"}}));
  assert.equal(barcode.source,"inventory");
  assert.equal(barcode.item.id,itemId);
  const received=parseTool(await client.callTool({name:"record_receipt",arguments:{itemId,locationId,quantity:2,idempotencyKey:"mcp-receipt",expiryDate:"2027-01-01"}}));
  assert.equal(received.beforeQuantity,0);
  assert.equal(received.afterQuantity,2);
  const overview=parseTool(await client.callTool({name:"get_home_overview",arguments:{}}));
  assert.equal(overview.needsReplenishment.total,1);
  const mcpCalendar=parseTool(await client.callTool({name:"get_shopping_calendar",arguments:{month:"2026-10"}}));
  assert.equal(mcpCalendar[0].channelName,channels[0].name);
  await client.close();await server.close();

  const accountServer=createMcpServer((method,url,body)=>request(accountToken,method,url,body));
  const accountClient=new Client({name:"account-test",version:"1"});
  const [accountClientTransport,accountServerTransport]=InMemoryTransport.createLinkedPair();
  await accountServer.connect(accountServerTransport);await accountClient.connect(accountClientTransport);
  const accountTools=await accountClient.listTools();
  assert.equal("homeId" in (accountTools.tools.find(tool=>tool.name==="record_receipt")!.inputSchema.properties??{}),true);
  await accountClient.close();await accountServer.close();await app.close();db.close();
});
