import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import type { FastifyReply, FastifyRequest } from "fastify";
import { barcodeSchema, consumptionTypeSchema, itemIconSchema } from "@al1s-wms/contracts";
import { z } from "zod";

export type ApiCall = (method: "GET" | "POST" | "PATCH" | "DELETE", url: string, body?: Record<string, unknown>) => Promise<{ status: number; body: unknown }>;
const homeId = z.string().uuid().describe("Home ID from list_homes");
const itemId = z.string().uuid().describe("Item ID from search_items");
const locationId = z.string().uuid().describe("Location ID from list_locations");
const name = z.string().trim().min(1).max(200);
const quantity = z.number().positive().finite();
const price = z.number().nonnegative().finite().max(1_000_000_000);
const idempotencyKey = z.string().trim().min(1).max(200).describe("Unique key for this operation. Reuse the same key and payload only when retrying.");
const dates = { manufacturedDate: z.string().date().nullable().optional(), expiryDate: z.string().date().nullable().optional() };
const paging = { limit: z.number().int().min(1).max(100).optional().describe("Page size, default 50"), offset: z.number().int().nonnegative().optional().describe("Zero-based offset; use nextOffset from previous result") };
const query = (args: Record<string, unknown>) => new URLSearchParams(Object.entries(args).filter(([, v]) => v !== undefined && v !== null).map(([k,v])=>[k,String(v)])).toString();
const homePath = (id: string) => `/api/v1/homes/${id}`;

// MCP is an authenticated adapter over the same application routes as Web.
export function createMcpServer(api: ApiCall, boundHomeId: string | null = null) {
  const server = new McpServer({ name: "AL1S-WMS", version: "0.5.0" });
  const homeInput: z.ZodRawShape = boundHomeId ? {} : {homeId};
  const scoped = (shape: z.ZodRawShape = {}) => ({...homeInput,...shape});
  const context = (args: Record<string,unknown>) => {
    const {homeId:requestedHomeId,...body}=args;
    return {homeId:boundHomeId??String(requestedHomeId),body};
  };
  const atHome = (args: Record<string,unknown>, suffix: string) => {
    const value=context(args);
    return {url:`${homePath(value.homeId)}${suffix}`,body:value.body};
  };
  const register = (tool: string, description: string, inputSchema: z.ZodRawShape, method: "GET" | "POST" | "PATCH" | "DELETE", route: (args: any) => { url: string; body?: Record<string, unknown> }) => {
    server.registerTool(tool, {
      description, inputSchema,
      annotations: { readOnlyHint: method === "GET", destructiveHint: method === "DELETE", openWorldHint: false },
    }, async args => {
      const { url, body } = route(args);
      const result = body && Object.keys(body).length ? await api(method, url, body) : await api(method, url);
      return { isError: result.status >= 400, content: [{ type: "text" as const, text: JSON.stringify(result.body) }] };
    });
  };
  const text = (value:unknown) => ({content:[{type:"text" as const,text:JSON.stringify(value)}]});
  server.registerTool("get_home_context", {
    description:"Start here. Returns the home or homes this token may manage and whether homeId is required by other tools.",
    inputSchema:{},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},
  }, async()=>{
    const result=await api("GET","/api/v1/homes");
    const homes=Array.isArray(result.body)?result.body:[];
    return text({scope:boundHomeId?"home":"account",homeIdRequired:!boundHomeId,currentHome:boundHomeId?homes[0]??null:null,homes,recommendedNextTool:"get_home_overview"});
  });
  server.registerTool("get_agent_guide", {
    description:"Read the canonical workflows for overview, batch receipt, shopping receipt, and physical stock reconciliation.",
    inputSchema:{},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},
  }, async()=>text({
    rules:[
      "Call get_home_context first. Account-scoped tokens must pass homeId; home-scoped tokens never do.",
      "Call get_home_overview before proactive household management.",
      "Every retryable write needs a unique idempotencyKey. Reuse the same key only to retry the exact same payload.",
      "Quantities always use the item's baseUnit. Unit conversion is not supported.",
      "Stock activity descriptions are generated by the server. Do not store conversational narration in inventory history.",
    ],
    barcode:["lookup_barcode checks household inventory, local cache, then online databases","if inventory is returned, use that item instead of creating a duplicate","otherwise confirm the suggested metadata before create_item"],
    receipt:["search_items or lookup_barcode to resolve itemId","list_locations to resolve locationId","record_receipt once; every receipt creates a new batch and dates belong only to that batch","report beforeQuantity, afterQuantity, and created batch"],
    shoppingPlanning:["list_shopping_items includes pending manual purchases and dynamic automatic low-stock recommendations","update_shopping_item sets channelId and plannedDate; updating an auto:<itemId> recommendation materializes it as a pending purchase","get_shopping_calendar answers what to buy and where on a given month"],
    shoppingReceipt:["list_shopping_items","receive_shopping_item with actualQuantity, locationId when needed, totalPrice, purchaseDate, and optional batch dates","successful receipt removes the item from the active shopping list but retains its linked batch and financial history","do not update or delete the item first"],
    finance:["use get_financial_dashboard for monthly budgets and purchase spending; byCategory contains actual, planned, and budget, where budget null means unbudgeted spending","use get_inventory_cost_analysis for inbound, consumed, expired, damaged, and adjustment costs calculated from historical batch unit cost","report category forecast as actual + planned; negative budget remaining is over-budget","call get_financial_dashboard before proposing a budget change and get explicit user confirmation before set_financial_budget","set estimatedTotal on a shopping item for planning and totalPrice when receiving it; the actual cost is stored on the new batch","use get_item_price_history to compare channels and past unit prices"],
    expiredHandling:["get_home_overview returns the exact expired batchId and remaining quantity","confirm disposal or consumption with the user","record_issue with that batchId, quantity, and issueReason expired"],
    stocktake:["search_items and list_locations","reconcile_stock with countedQuantity for one item at one location","positive differences create a new batch; negative differences consume FEFO unless batchId is supplied","report difference and affected batches"],
    longTermConsumables:["record_issue on a long_term_consumable opens the selected stock without decreasing inventory","list_opened_consumables shows all opened records","confirm the item and quantity before exhaust_opened_consumable; only that action decreases stock"],
  }));
  register("list_homes", boundHomeId?"Return the single home bound to this token.":"List homes available to this account token; choose one homeId before other calls.", {}, "GET", () => ({ url: "/api/v1/homes" }));
  const homeFields = { name: name.max(80), icon: z.enum(["house", "building", "trees", "warehouse", "castle", "leaf", "star"]).describe("Built-in family icon"),defaultCurrency:z.enum(["CNY","USD","EUR","JPY","GBP","HKD"]).optional() };
  if(!boundHomeId)register("create_home", "Create a home with built-in categories and no locations. Available only to account-scoped tokens.", homeFields, "POST", body=>({url:"/api/v1/homes",body}));
  register("update_home", "Edit the selected home name, icon, and default currency. Name and icon are required.", scoped(homeFields), "PATCH", args=>{const value=context(args);return {url:homePath(value.homeId),body:value.body};});
  register("get_home_overview", "Primary proactive-management call. Summarizes low stock, expiring batches, expired batches, pending purchases, and recommended actions.", scoped({
    expiryDays:z.number().int().min(1).max(365).optional().describe("Upcoming expiry window; default 30 days"),limit:z.number().int().min(1).max(50).optional().describe("Maximum rows per section; default 10"),
  }), "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/overview?${query(value.body)}`};});
  register("get_financial_summary", "Return compact monthly actual and planned purchase spending, budget position, and channel totals for one YYYY-MM month. Use get_inventory_cost_analysis for consumption and waste.", scoped({month:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/)}), "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/financial-summary?${query(value.body)}`};});
  register("get_spending_trend", "Monthly financial trend over an inclusive start/end YYYY-MM range, up to 36 months. Includes actual spending, pending plans, monthly budgets, prior equal-length period and prior-year comparisons. Incomplete periods compare through matching elapsed dates; percent is null when the baseline is zero.", scoped({start:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),end:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/)}), "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/financial-trend?${query(value.body)}`};});
  register("list_purchase_records", "Page through purchases by inclusive stock receipt date range (YYYY-MM-DD). Sorted newest first; returns total count and amount for the entire range, not just the page. page starts at 1; pageSize is at most 100.", scoped({start:z.string().date(),end:z.string().date(),page:z.number().int().min(1).optional(),pageSize:z.number().int().min(1).max(100).optional()}), "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/purchase-records?${query(value.body)}`};});
  register("get_financial_dashboard", "Return complete monthly budget and purchase-spending data: total budget position, trend, purchase records, channel totals, and category execution. Actual spending follows batch receipt time (received_at), not plannedDate or purchaseDate. Planned amounts follow planned dates. Budgeted parent rows include descendant spending, so do not sum overlapping rows; use dashboard totals.", scoped({month:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/)}), "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/financial-dashboard?${query(value.body)}`};});
  register("get_inventory_cost_analysis", "Analyze inventory cost over an inclusive YYYY-MM range (up to 36 months). Returns inbound purchase cost, normal consumption, expired and damaged waste, adjustments, waste rate, item/category/location waste rankings, receipt-month cohorts and current 30-day expiry risk. Cohorts and waste-ranking batch details use cumulative outcomes through asOf (default today); usedShare is consumed cost divided by original batch cost. Period waste uses event dates. Location rankings show whole affected-batch costs, which must not be summed across locations. Issue values use each actual batch's historical unit cost; unknown costs are reported separately.", scoped({asOf:z.string().date().optional(),start:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),end:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/)}), "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/inventory-cost-analysis?${query({...value.body,granularity:"month"})}`};});
  register("set_financial_budget", "Set or clear one month's total budget and category allocations. Confirm the exact amounts with the user immediately before calling: this replaces that month's allocations. Parent budgets include all descendants. Child budgets reserve part of their nearest ancestor budget; their combined amounts must fit within it. Only outermost category budgets count toward the monthly total. When adding a new child allocation, increase each ancestor total by that amount to preserve existing direct allocations; when setting a parent's total explicitly, retain its child amounts. A null total with category budgets derives the monthly total from those outermost budgets; null with no categories clears the month; later months inherit the latest budget until explicitly saved.", scoped({month:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),total:price.nullable(),categoryBudgets:z.array(z.object({category:name.max(100),amount:price})).max(100)}), "PATCH", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/financial-budget`,body:value.body};});
  register("get_item_price_history", "Return batch-level total and unit purchase prices for one item, ordered newest first.", scoped({itemId}), "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/items/${value.body.itemId}/price-history`};});
  register("lookup_barcode", "Resolve a GTIN/EAN/UPC. Checks household inventory and local cache first, then ApiZero for Chinese barcodes and the Open Facts databases. Use returned fields to confirm create_item input.", scoped({barcode:barcodeSchema}), "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/barcodes/${value.body.barcode}`};});
  register("search_items", "Search inventory for stocktake or maintenance. Returns a page object; location and category filters include descendants by default.", scoped({
    query: name.optional(), category: name.optional(), locationId: locationId.optional(),
    includeDescendantLocations: z.boolean().optional(), includeDescendantCategories: z.boolean().optional(),
    lowStockOnly: z.boolean().optional(), expiryBefore: z.string().date().optional(), ...paging,
  }), "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/items?${query({...value.body,paged:true})}`};});
  register("get_item", "Get one active item and its stock/nearest-expiry summary. Use list_batches for batch detail.", scoped({itemId}), "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/items/${value.body.itemId}`};});
  register("get_stock", "Get balances per location, optionally filtered by item, location, or batch.", scoped({itemId:itemId.optional(),locationId:locationId.optional(),batchId:z.string().uuid().optional()}), "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/stock?${query(value.body)}`};});
  const consumptionType=consumptionTypeSchema.describe("consumable: issue immediately decreases stock; long_term_consumable: issue opens reserved stock and exhaust_opened_consumable later decreases it; non_consumable: issue removes stock for disposal, loss, or damage.");
  const itemFields = { name, barcode:barcodeSchema.optional(),icon: itemIconSchema.nullable().optional().describe("Explicit built-in icon; null restores automatic display matching"), category:name.optional(), baseUnit:name.max(30), consumptionType:consumptionType.optional(), openedShelfLifeDays:z.number().int().positive().nullable().optional().describe("Optional default shelf life in days after opening a long-term consumable. Opening automatically records an opened expiry date, capped by the batch expiry."), reorderPoint:z.number().nonnegative().optional(),locationId:locationId.optional() };
  register("create_item", "Create an item. initialQuantity requires locationId; dates and purchase cost describe only its opening batch.", scoped({...itemFields,initialQuantity:z.number().nonnegative().optional(),totalPrice:price.optional(),purchaseDate:z.string().date().nullable().optional(),channelId:z.string().uuid().nullable().optional(),...dates}), "POST", args=>{const value=context(args);const {initialQuantity=0,...body}=value.body;return {url:`${homePath(value.homeId)}/items`,body:{category:"其他",reorderPoint:0,reorderQuantity:0,...body,initialStock:initialQuantity}};});
  register("update_item", "Edit item master data. Changing location moves existing stock there while preserving batches. Use update_batch for dates. Unit conversion is not supported.", {
    ...homeInput,itemId,name:name.optional(),barcode:barcodeSchema.nullable().optional(),icon:itemFields.icon,category:name.optional(),baseUnit:name.max(30).optional(),consumptionType:consumptionType.optional(),openedShelfLifeDays:itemFields.openedShelfLifeDays,reorderPoint:z.number().nonnegative().optional(),locationId:locationId.nullable().optional(),
  }, "PATCH", args=>{const value=context(args);const {itemId,...body}=value.body;return {url:`${homePath(value.homeId)}/items/${itemId}`,body};});
  for(const [kind,resource] of [["location","locations"],["category","categories"]] as const) {
    register(`list_${resource}`, `List active ${kind} tree nodes with id, name, and parentId. Resolve IDs before inventory writes.`, scoped(), "GET", args=>atHome(args,`/${resource}`));
    register(`create_${kind}`, `Add a ${kind} node. Omit parentId for a root.`, scoped({name,parentId:z.string().uuid().optional()}), "POST", args=>atHome(args,`/${resource}`));
    register(`update_${kind}`, "Rename or move a node. parentId is required; null makes it a root.", scoped({[`${kind}Id`]:z.string().uuid(),name,parentId:z.string().uuid().nullable()}), "PATCH", args=>{const value=context(args);const nodeId=value.body[`${kind}Id`];return {url:`${homePath(value.homeId)}/${resource}/${nodeId}`,body:{name:value.body.name,parentId:value.body.parentId}};});
  }
  for(const [kind,resource] of [["item","items"],["category","categories"],["location","locations"]] as const) {
    register(`delete_${kind}`, kind==="item" ? "Destructive: delete an item and remaining stock after user confirmation; history is retained." : "Destructive: delete a node after user confirmation; children and direct items are promoted.", scoped({[`${kind}Id`]:z.string().uuid()}), "DELETE", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/${resource}/${value.body[`${kind}Id`]}`};});
  }
  register("list_transactions", "Page through item-only history; no node or home events. Returns {items,total,hasMore,nextOffset,snapshotAt}. Reuse snapshotAt and nextOffset for consistent pagination.", {
    ...homeInput,itemId:itemId.optional(),locationId:locationId.optional(),batchId:z.string().uuid().optional(),query:name.optional(),
    type:z.enum(["receipt","issue","delete","reclassify","move","update"]).optional(),
    occurredFrom:z.string().datetime().optional(),occurredTo:z.string().datetime().optional(),snapshotAt:z.string().datetime().optional(),...paging,
  }, "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/transactions?${query(value.body)}`};});
  register("list_shopping_items", "List active manual purchases and dynamic automatic low-stock recommendations. Received purchases are not returned; their history is available through financial dashboard purchase records and batches.", scoped(), "GET", args=>atHome(args,"/shopping-list"));
  const shoppingItemId=z.string().regex(/^(auto:)?[0-9a-f-]{36}$/i);
  const shoppingFields = {itemId:itemId.nullable().optional(),name:name.optional(),quantity:quantity.optional(),unit:name.max(30).optional(),category:name.optional(),locationId:locationId.nullable().optional(),channelId:z.string().uuid().nullable().optional(),plannedDate:z.string().date().nullable().optional(),estimatedTotal:price.nullable().optional()};
  register("create_shopping_item", "Create a purchase. Link itemId when buying known inventory; standalone purchases require name, unit, category, and locationId.", scoped(shoppingFields), "POST", args=>atHome(args,"/shopping-list"));
  register("update_shopping_item", "Edit a pending purchase, its purchase channel, or planned date. Updating an auto:<itemId> recommendation turns it into a persisted purchase.", scoped({shoppingItemId,...shoppingFields}), "PATCH", args=>{const value=context(args);const {shoppingItemId,...body}=value.body;return {url:`${homePath(value.homeId)}/shopping-list/${shoppingItemId}`,body};});
  register("receive_shopping_item", "Complete a purchase as one new batch. totalPrice is the actual amount paid and purchase channel is inherited from the plan. On success it leaves the active shopping list, while shoppingItemId remains linked on the batch for financial history.", scoped({shoppingItemId,actualQuantity:quantity,idempotencyKey,locationId:locationId.optional(),totalPrice:price.optional(),purchaseDate:z.string().date().nullable().optional(),...dates}), "POST", args=>{const value=context(args);const {shoppingItemId,...body}=value.body;return {url:`${homePath(value.homeId)}/shopping-list/${encodeURIComponent(String(shoppingItemId))}/receive`,body};});
  register("delete_shopping_item", "Delete a pending manual purchase without changing stock. Automatic recommendations cannot be deleted.", scoped({shoppingItemId:z.string().uuid()}), "DELETE", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/shopping-list/${value.body.shoppingItemId}`};});
  register("list_shopping_channels", "List available purchase channels such as online platforms and supermarkets.", scoped(), "GET", args=>atHome(args,"/shopping-channels"));
  register("create_shopping_channel", "Add a purchase channel. Channels are intentionally flat, without store sections.", scoped({name:name.max(80)}), "POST", args=>atHome(args,"/shopping-channels"));
  register("update_shopping_channel", "Rename a purchase channel.", scoped({channelId:z.string().uuid(),name:name.max(80)}), "PATCH", args=>{const value=context(args);const {channelId,...body}=value.body;return {url:`${homePath(value.homeId)}/shopping-channels/${channelId}`,body};});
  register("delete_shopping_channel", "Hide a purchase channel. Existing purchase history retains its channel name.", scoped({channelId:z.string().uuid()}), "DELETE", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/shopping-channels/${value.body.channelId}`};});
  register("get_shopping_calendar", "List planned purchases for one YYYY-MM month, including item, quantity, planned date, and purchase channel.", scoped({month:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),includeCompleted:z.boolean().optional()}), "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/shopping-calendar?${query(value.body)}`};});
  for(const type of ["receipt","issue"] as const) {
    register(`record_${type}`, type==="receipt" ? "Receive stock as a new batch with optional production and expiry dates." : "For consumable and non_consumable items, issue immediately decreases stock. For long_term_consumable items, issue opens reserved stock without decreasing inventory; call exhaust_opened_consumable when it is used up.", {
      ...homeInput,itemId,locationId,quantity,idempotencyKey,...(type==="receipt" ? {...dates,totalPrice:price.optional(),purchaseDate:z.string().date().nullable().optional(),channelId:z.string().uuid().nullable().optional()} : {batchId:z.string().uuid().optional(),issueReason:z.enum(["used","expired","damaged"]).describe("Why stock leaves inventory: normal use, expired disposal, or damage")}),
    }, "POST", args=>atHome(args,`/stock/${type}`));
  }
  register("list_opened_consumables", "List all opened long-term consumables. Each row remains in stock until exhausted.", scoped(), "GET", args=>atHome(args,"/opened-consumables"));
  register("exhaust_opened_consumable", "Write action: after explicit confirmation, mark an opened long-term consumable as used up and decrease its stock. Omit quantity to exhaust the entire opened record.", scoped({openedId:z.string().uuid(),quantity:quantity.optional(),idempotencyKey,reason:z.string().trim().max(200).optional()}), "POST", args=>{const value=context(args);const {openedId,...body}=value.body;return {url:`${homePath(value.homeId)}/opened-consumables/${openedId}/exhaust`,body};});
  register("reconcile_stock", "Physical stocktake: set the counted quantity for one item at one location. Positive differences create a dated batch; negative differences consume FEFO or batchId. The server records the activity description.", scoped({itemId,locationId,countedQuantity:z.number().nonnegative().finite(),idempotencyKey,batchId:z.string().uuid().optional(),...dates}), "POST", args=>atHome(args,"/stock/reconcile"));
  register("transfer_stock", "Transfer stock between locations without changing total stock or batch identity. Omit batchId for FEFO. The server records the source and target as the activity description.", scoped({itemId,sourceLocationId:locationId,targetLocationId:locationId,quantity,idempotencyKey,batchId:z.string().uuid().optional()}), "POST", args=>atHome(args,"/stock/transfers"));
  register("list_batches", "List batch balances per location, ordered by expiry. includeEmpty also returns consumed batches.", scoped({itemId:itemId.optional(),locationId:locationId.optional(),includeEmpty:z.boolean().optional(),...paging}), "GET", args=>{const value=context(args);return {url:`${homePath(value.homeId)}/batches?${query(value.body)}`};});
  register("update_batch", "Correct one batch label, dates, actual total price, purchase date, or channel. Null clears a value.", scoped({batchId:z.string().uuid(),label:name.max(100).nullable().optional(),totalPrice:price.nullable().optional(),purchaseDate:z.string().date().nullable().optional(),channelId:z.string().uuid().nullable().optional(),...dates}), "PATCH", args=>{const value=context(args);const {batchId,...body}=value.body;return {url:`${homePath(value.homeId)}/batches/${batchId}`,body};});
  return server;
}

export async function handleMcpRequest(request: FastifyRequest, reply: FastifyReply, api: ApiCall, boundHomeId: string | null = null) {
  const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
  const server = createMcpServer(api,boundHomeId);
  await server.connect(transport);
  reply.hijack();
  reply.raw.on("close", () => { void server.close(); });
  await transport.handleRequest(request.raw, reply.raw, request.body);
}
